name: laravel_auth_slate
description: Laravel authentication Slate package, creates a login, signup and api service using Sanctum.
version: 0.0.1
homepage: https://nylo.dev
repository: https://github.com/nylo-core/laravel_auth_slate
issue_tracker: https://github.com/nylo-core/laravel_auth_slate/issues
documentation: https://github.com/nylo-core/laravel_auth_slate

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  args: ^2.3.2
  nylo_support: 5.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

screenshots:
  - description: The package logo.
    path: screenshots/logo.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
