name: laravel_auth_slate
description: Laravel authentication package, creates a login, signup and api service using Sanctum.
version: 1.0.11
homepage: https://nylo.dev
repository: https://github.com/nylo-core/laravel_auth_slate
issue_tracker: https://github.com/nylo-core/laravel_auth_slate/issues
documentation: https://github.com/nylo-core/laravel_auth_slate
funding:
  - https://github.com/sponsors/agordn52
topics:
  - laravel-auth
  - laravel-ui
  - laravel-flutter

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  args: ^2.4.2
  nylo_support: ^5.41.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

screenshots:
  - description: The package logo.
    path: screenshots/logo.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
